name: Build

permissions:
  contents: read
  security-events: write 
  pull-requests: write
  actions: read
  checks: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          enable-comments: true
          enable-summary: true
      - name: Semgrep scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/csharp
          output: semgrep.sarif
          generateSarif: "1"

  build:
    needs: security
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: |
            Library
            Temp
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-
      - name: Build Unity Project
        uses: game-ci/unity-builder@v5.0.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          ANDROID_KEYALIAS_NAME: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          ANDROID_KEYALIAS_PASS: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        with:
          targetPlatform: Android
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/Android